package com.dct.survey.taishan.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dct.survey.taishan.bean.Dictionary;
import com.dct.survey.taishan.bean.SurveyTarget;

import com.dct.survey.taishan.dao.DictionaryDao;
import com.dct.survey.taishan.dao.SurveyTargetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dictionaryDaoConfig;
    private final DaoConfig surveyTargetDaoConfig;

    private final DictionaryDao dictionaryDao;
    private final SurveyTargetDao surveyTargetDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dictionaryDaoConfig = daoConfigMap.get(DictionaryDao.class).clone();
        dictionaryDaoConfig.initIdentityScope(type);

        surveyTargetDaoConfig = daoConfigMap.get(SurveyTargetDao.class).clone();
        surveyTargetDaoConfig.initIdentityScope(type);

        dictionaryDao = new DictionaryDao(dictionaryDaoConfig, this);
        surveyTargetDao = new SurveyTargetDao(surveyTargetDaoConfig, this);

        registerDao(Dictionary.class, dictionaryDao);
        registerDao(SurveyTarget.class, surveyTargetDao);
    }
    
    public void clear() {
        dictionaryDaoConfig.clearIdentityScope();
        surveyTargetDaoConfig.clearIdentityScope();
    }

    public DictionaryDao getDictionaryDao() {
        return dictionaryDao;
    }

    public SurveyTargetDao getSurveyTargetDao() {
        return surveyTargetDao;
    }

}
