package com.dct.survey.taishan.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dct.survey.taishan.bean.SurveyTarget;
import com.dct.survey.taishan.bean.UserBean;
import com.dct.survey.taishan.bean.DictionaryLibrary;
import com.dct.survey.taishan.bean.WorkSiteBean;

import com.dct.survey.taishan.dao.SurveyTargetDao;
import com.dct.survey.taishan.dao.UserBeanDao;
import com.dct.survey.taishan.dao.DictionaryLibraryDao;
import com.dct.survey.taishan.dao.WorkSiteBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig surveyTargetDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig dictionaryLibraryDaoConfig;
    private final DaoConfig workSiteBeanDaoConfig;

    private final SurveyTargetDao surveyTargetDao;
    private final UserBeanDao userBeanDao;
    private final DictionaryLibraryDao dictionaryLibraryDao;
    private final WorkSiteBeanDao workSiteBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        surveyTargetDaoConfig = daoConfigMap.get(SurveyTargetDao.class).clone();
        surveyTargetDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        dictionaryLibraryDaoConfig = daoConfigMap.get(DictionaryLibraryDao.class).clone();
        dictionaryLibraryDaoConfig.initIdentityScope(type);

        workSiteBeanDaoConfig = daoConfigMap.get(WorkSiteBeanDao.class).clone();
        workSiteBeanDaoConfig.initIdentityScope(type);

        surveyTargetDao = new SurveyTargetDao(surveyTargetDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        dictionaryLibraryDao = new DictionaryLibraryDao(dictionaryLibraryDaoConfig, this);
        workSiteBeanDao = new WorkSiteBeanDao(workSiteBeanDaoConfig, this);

        registerDao(SurveyTarget.class, surveyTargetDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(DictionaryLibrary.class, dictionaryLibraryDao);
        registerDao(WorkSiteBean.class, workSiteBeanDao);
    }
    
    public void clear() {
        surveyTargetDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        dictionaryLibraryDaoConfig.clearIdentityScope();
        workSiteBeanDaoConfig.clearIdentityScope();
    }

    public SurveyTargetDao getSurveyTargetDao() {
        return surveyTargetDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public DictionaryLibraryDao getDictionaryLibraryDao() {
        return dictionaryLibraryDao;
    }

    public WorkSiteBeanDao getWorkSiteBeanDao() {
        return workSiteBeanDao;
    }

}
